### ISSUE TITLE
Error while downloading using post list

### ISSUE THREAD

**Issue by rexendevar** [josephrcox/easy-reddit-downloader#73]
Hello, it's quite late so I'm not going to do much troubleshooting, but I keep getting this error piling up in my logs and it's making the script unable to download anything I think.

```
(node:108590) UnhandledPromiseRejectionWarning: Error: connect EHOSTUNREACH 199.232.149.140:443
    at Function.AxiosError.from (/home/spyndling/.packages/easy-reddit-downloader-0.3.0/node_modules/axios/dist/node/axios.cjs:785:14)
    at RedirectableRequest.handleRequestError (/home/spyndling/.packages/easy-reddit-downloader-0.3.0/node_modules/axios/dist/node/axios.cjs:2733:25)
    at RedirectableRequest.emit (events.js:314:20)
    at ClientRequest.eventHandlers.<computed> (/home/spyndling/.packages/easy-reddit-downloader-0.3.0/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:108590) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 956)

```

**Comment by rexendevar** [comment]
this apparently only happens with the latest RELEASE version and not the main github version. oopsi

**Comment by NoExplorer** [comment]
From a quick search online, the error `EHOSTUNREACH` might be being caused by your firewall blocking the port the program is trying to use (`..:443`). Try whitelisting the program in your firewall's settings.

**Comment by josephrcox** [comment]
@rexendevar Did you try @NoExplorer's suggestion? It may also be possible that Reddit is blocking you for some reason.
